### ISSUE TITLE
More updates?

### ISSUE THREAD

**Issue by Charlyo** [briankendall/qBittorrent-10.13-compatible-releases#1]
Dear @briankendall !

Thank you for your work!

Can you please release the newest version?

**Comment by briankendall** [comment]
I'll try to get to it soon. I've been slacking on this because I'm staying on an earlier version of qBittorrent. The later releases have proven unstable for me. 🙁

**Comment by gennaios** [comment]
4.5.x has also been unstable for me. Looking at their bug reports, one in a particular seems to track the main macOS crashes though I'm not sure if such applies here.

https://github.com/qbittorrent/qBittorrent/issues/19090

**Comment by briankendall** [comment]
I just made a build of 4.5.5 using the latest version of Qt 5.15, for those of you that want it. I'm still sticking with qbt 4.3.9 for the time being, though.
